/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package decafbot.scala;

public final class R {
    public static final class array {
        public static final int gtw_strategies=0x7f050000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int choose_button=0x7f060003;
        public static final int game_chooser_list=0x7f060000;
        public static final int game_global_thermonuclear_war=0x7f060002;
        public static final int game_guess_the_number=0x7f060001;
        public static final int gtw_strategy_list=0x7f060004;
        public static final int guess=0x7f060006;
        public static final int prompt=0x7f060005;
        public static final int submit_button=0x7f060007;
    }
    public static final class layout {
        public static final int game_chooser=0x7f030000;
        public static final int global_thermonuclear_war=0x7f030001;
        public static final int guess_the_number=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int choose_button_text=0x7f040001;
        public static final int choose_game=0x7f040002;
        public static final int chooser_confirm_nuke=0x7f040006;
        public static final int game_name_global_thermonuclear_war=0x7f040005;
        public static final int game_name_guess_the_number=0x7f040004;
        public static final int greetings=0x7f040003;
        public static final int gtn_end_dialog=0x7f040015;
        public static final int gtn_feedback_prompt=0x7f04000e;
        public static final int gtn_initial_prompt=0x7f04000d;
        public static final int gtn_not_a_number=0x7f04000f;
        public static final int gtn_player_lost=0x7f040014;
        public static final int gtn_player_won=0x7f040013;
        public static final int gtn_thinking=0x7f040012;
        public static final int gtn_too_high=0x7f040011;
        public static final int gtn_too_low=0x7f040010;
        public static final int gtw_conclusion=0x7f040009;
        public static final int gtw_testing_strategies=0x7f040008;
        public static final int guess=0x7f04000c;
        public static final int later=0x7f040007;
        public static final int no_thanks=0x7f04000b;
        public static final int sure=0x7f04000a;
    }
}
