/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class decafbot_jni_GuessTheNumberActivity */

#ifndef _Included_decafbot_jni_GuessTheNumberActivity
#define _Included_decafbot_jni_GuessTheNumberActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef decafbot_jni_GuessTheNumberActivity_PLAYER_LOST
#define decafbot_jni_GuessTheNumberActivity_PLAYER_LOST -2L
#undef decafbot_jni_GuessTheNumberActivity_TOO_LOW
#define decafbot_jni_GuessTheNumberActivity_TOO_LOW -1L
#undef decafbot_jni_GuessTheNumberActivity_PLAYER_WON
#define decafbot_jni_GuessTheNumberActivity_PLAYER_WON 0L
#undef decafbot_jni_GuessTheNumberActivity_TOO_HIGH
#define decafbot_jni_GuessTheNumberActivity_TOO_HIGH 1L
/*
 * Class:     decafbot_jni_GuessTheNumberActivity
 * Method:    nativeInitGame
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_decafbot_jni_GuessTheNumberActivity_nativeInitGame
  (JNIEnv *, jobject, jint);

/*
 * Class:     decafbot_jni_GuessTheNumberActivity
 * Method:    analyzeGuess
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_decafbot_jni_GuessTheNumberActivity_analyzeGuess
  (JNIEnv *, jobject, jint);

/*
 * Class:     decafbot_jni_GuessTheNumberActivity
 * Method:    guessesLeft
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_decafbot_jni_GuessTheNumberActivity_guessesLeft
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
